console.log("TAXI TIME ADMIN SECURE • SHARED QUBA↔BAKI + BAKU LOCATIONS işləyir");
let data={};
const API="https://taxitime-api.taxitime0711.workers.dev";
let adminAuth=sessionStorage.getItem("taxitime_admin_auth")||"";
const emptySlot=(start="",end="")=>({start,end,standard:"",standard_round_trip:"",comfort:"",comfort_round_trip:"",vip:"",vip_round_trip:"",one_way:"",round_trip:""});
const defaultSlots=()=>[emptySlot("06:00","20:00"),emptySlot("20:00","00:00"),emptySlot("00:00","06:00")];
const BAKU_DISTRICTS=["Binəqədi","Xətai","Xəzər","Qaradağ","Nərimanov","Nəsimi","Nizami","Pirallahı","Sabunçu","Səbail","Suraxanı","Yasamal"];
const BAKU_STARTER_LOCATIONS={
  "Binəqədi":[["Biləcəri","Qəsəbə"],["Binəqədi qəsəbəsi","Qəsəbə"],["Xocəsən","Qəsəbə"],["Sulutəpə","Qəsəbə"],["28 May qəsəbəsi","Qəsəbə"],["6-cı mikrorayon","Mikrorayon"],["7-ci mikrorayon","Mikrorayon"],["8-ci mikrorayon","Mikrorayon"],["9-cu mikrorayon","Mikrorayon"]],
  "Xətai":[["Əhmədli","Məhəllə"],["Həzi Aslanov","Məhəllə"],["Ağ Şəhər","Məhəllə"],["Babək prospekti","Prospekt"],["Nobel prospekti","Prospekt"],["Xocalı prospekti","Prospekt"]],
  "Xəzər":[["Mərdəkan","Qəsəbə"],["Buzovna","Qəsəbə"],["Şüvəlan","Qəsəbə"],["Binə","Qəsəbə"],["Qala","Qəsəbə"],["Türkan","Qəsəbə"],["Zirə","Qəsəbə"],["Şağan","Qəsəbə"]],
  "Qaradağ":[["Lökbatan","Qəsəbə"],["Sahil","Qəsəbə"],["Ələt","Qəsəbə"],["Qobustan","Qəsəbə"],["Puta","Qəsəbə"],["Korgöz","Qəsəbə"],["Səngəçal","Qəsəbə"],["Ümid","Qəsəbə"]],
  "Nərimanov":[["Gənclik","Məhəllə"],["Montin","Məhəllə"],["Nəriman Nərimanov","Məhəllə"],["Atatürk prospekti","Prospekt"],["Təbriz küçəsi","Küçə"],["Ağa Neymətulla küçəsi","Küçə"]],
  "Nəsimi":[["28 May","Məhəllə"],["3-cü mikrorayon","Mikrorayon"],["4-cü mikrorayon","Mikrorayon"],["Tbilisi prospekti","Prospekt"],["Azadlıq prospekti","Prospekt"],["Səməd Vurğun küçəsi","Küçə"]],
  "Nizami":[["8-ci km","Məhəllə"],["Qara Qarayev","Məhəllə"],["Neftçilər","Məhəllə"],["Keşlə","Qəsəbə"],["Heydər Əliyev prospekti","Prospekt"],["Qara Qarayev prospekti","Prospekt"]],
  "Pirallahı":[["Pirallahı qəsəbəsi","Qəsəbə"],["Çilov","Qəsəbə"],["Neft Daşları","Qəsəbə"]],
  "Sabunçu":[["Bakıxanov","Qəsəbə"],["Zabrat","Qəsəbə"],["Ramana","Qəsəbə"],["Maştağa","Qəsəbə"],["Bilgəh","Qəsəbə"],["Kürdəxanı","Qəsəbə"],["Pirşağı","Qəsəbə"],["Nardaran","Qəsəbə"],["Savalan","Qəsəbə"]],
  "Səbail":[["İçərişəhər","Məhəllə"],["Badamdar","Qəsəbə"],["Bibiheybət","Qəsəbə"],["Bayıl","Qəsəbə"],["Neftçilər prospekti","Prospekt"],["İstiqlaliyyət küçəsi","Küçə"]],
  "Suraxanı":[["Yeni Günəşli","Qəsəbə"],["Köhnə Günəşli","Məhəllə"],["Suraxanı qəsəbəsi","Qəsəbə"],["Əmircan","Qəsəbə"],["Bülbülə","Qəsəbə"],["Hövsan","Qəsəbə"],["Qaraçuxur","Qəsəbə"],["Zığ","Qəsəbə"]],
  "Yasamal":[["Yeni Yasamal","Məhəllə"],["Yasamal","Məhəllə"],["20 Yanvar","Məhəllə"],["İnşaatçılar","Məhəllə"],["Elmlər Akademiyası","Məhəllə"],["Mətbuat prospekti","Prospekt"],["Şərifzadə küçəsi","Küçə"]]
};
function isObj(v){return !!v&&typeof v==="object"&&!Array.isArray(v);}
function val(...items){for(const x of items){if(x!==undefined&&x!==null&&String(x).trim()!=="")return x;}return "";}
function clone(v){return JSON.parse(JSON.stringify(v||{}));}
function normalizeSlot(src={}){const s=isObj(src)?src:{};const standard=val(s.standard,s.one_way);const standardRound=val(s.standard_round_trip,s.standard_round,s.round_trip);return {...s,start:val(s.start,""),end:val(s.end,""),standard,standard_round_trip:standardRound,comfort:val(s.comfort,""),comfort_round_trip:val(s.comfort_round_trip,s.comfort_round,""),vip:val(s.vip,""),vip_round_trip:val(s.vip_round_trip,s.vip_round,""),one_way:standard,round_trip:standardRound};}
function mergeWholeCarSource(base,preferred){const b=isObj(base)?base:{};const p=isObj(preferred)?preferred:{};return {...b,...p,regions:{...(isObj(b.regions)?b.regions:{}),...(isObj(p.regions)?p.regions:{})},baku_locations:{...(isObj(b.baku_locations)?b.baku_locations:{}),...(isObj(p.baku_locations)?p.baku_locations:{})}};}
function normalizeBakuLocation(src={}){const s=isObj(src)?src:{};return {...s,name:val(s.name,""),type:val(s.type,"Digər"),standard:val(s.standard,s.one_way),standard_round:val(s.standard_round,s.standard_round_trip,s.round_trip),comfort:val(s.comfort,""),comfort_round:val(s.comfort_round,s.comfort_round_trip),vip:val(s.vip,""),vip_round:val(s.vip_round,s.vip_round_trip)};}
function ensureBakuDistricts(seedStarter=false){data.prices.baku_locations=isObj(data.prices.baku_locations)?data.prices.baku_locations:{};for(const district of BAKU_DISTRICTS){let obj=data.prices.baku_locations[district];if(!isObj(obj))obj={};let locations=Array.isArray(obj.locations)?obj.locations.map(normalizeBakuLocation):[];if(seedStarter&&locations.length===0){locations=(BAKU_STARTER_LOCATIONS[district]||[]).map(([name,type])=>normalizeBakuLocation({name,type}));}data.prices.baku_locations[district]={...obj,locations};}}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".nav-btn").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".page").forEach(p=>p.classList.remove("active-page"));button.classList.add("active");document.getElementById(button.dataset.page)?.classList.add("active-page");}));if(adminAuth)unlockAdmin();document.getElementById("adminPass")?.addEventListener("keydown",e=>{if(e.key==="Enter")adminLogin();});});
async function adminLogin(){const u=document.getElementById("adminUser").value.trim();const p=document.getElementById("adminPass").value;if(!u||!p){loginError.textContent="İstifadəçi adı və parolu yazın.";return;}const auth="Basic "+btoa(unescape(encodeURIComponent(u+":"+p)));loginError.textContent="Yoxlanılır...";try{const r=await fetch(API,{method:"GET",headers:{"Authorization":auth}});if(r.status===401||r.status===403)throw new Error("İstifadəçi adı və ya parol yanlışdır");if(!r.ok)throw new Error("Server xətası: "+r.status);adminAuth=auth;sessionStorage.setItem("taxitime_admin_auth",auth);loginError.textContent="";unlockAdmin();}catch(e){loginError.textContent=e.message;}}
function unlockAdmin(){loginGate.style.display="none";adminLayout.classList.remove("locked");loadDataFile();}
function adminLogout(){sessionStorage.removeItem("taxitime_admin_auth");adminAuth="";location.reload();}
function tariff(v){if(isObj(v)&&Array.isArray(v.slots))return {...v,slots:v.slots.map(normalizeSlot)};const slots=defaultSlots();if(isObj(v))slots[0]=normalizeSlot(v);else if(v!==undefined&&v!==null&&String(v).trim()!=="")slots[0]=normalizeSlot({standard:v,one_way:v});return {slots};}
function migrate(){data.company=data.company||{};const oldPrices=isObj(data.prices)?data.prices:{};const oldFull=isObj(data.fullCarPrices)?data.fullCarPrices:{};const useLegacyFull=data.pricingMode!=="full_car_unified"&&Object.keys(oldFull).length>0;data.prices=useLegacyFull?mergeWholeCarSource(oldPrices,oldFull):oldPrices;data.prices.quba_baki=tariff(data.prices.quba_baki||data.prices.baki_quba);data.prices.baki_quba=clone(data.prices.quba_baki);data.prices.regions=isObj(data.prices.regions)?data.prices.regions:{};Object.keys(data.prices.regions).forEach(r=>data.prices.regions[r]=tariff(data.prices.regions[r]));const hadBaku=Object.keys(isObj(data.prices.baku_locations)?data.prices.baku_locations:{}).length>0;ensureBakuDistricts(!hadBaku);data.pricingMode="full_car_unified";data.fullCarPrices=clone(data.prices);}
function loadDataFile(){fetch(API+"?ts="+Date.now(),{headers:{"Authorization":adminAuth}}).then(r=>{if(r.status===401||r.status===403)throw new Error("LOGIN_REQUIRED");return r.json();}).then(j=>{data=j;migrate();loadData();}).catch(e=>{if(e.message==="LOGIN_REQUIRED")adminLogout();else console.error(e);});}
function loadData(){companyName.value=data.company.name||"";city.value=data.company.city||"";phone.value=data.company.phone||"";whatsapp.value=data.company.whatsapp||"";renderSharedRouteSlots();loadBakuLocations();loadRegions();loadServices();loadCars();loadGallery();loadReviews();}
function priceInput(label,value,i,key,onchange){return `<div><label>${label}</label><input inputmode="decimal" value="${esc(value)}" placeholder="AZN / tam maşın" onchange="${onchange}(${i},'${key}',this.value)"></div>`;}
function slotHtml(s,i,onchange,del){return `<div class="tariff-row full-car-row"><div class="time-box"><label>Başlanğıc</label><input type="time" value="${esc(s.start||"")}" onchange="${onchange}(${i},'start',this.value)"></div><div class="time-box"><label>Bitmə</label><input type="time" value="${esc(s.end||"")}" onchange="${onchange}(${i},'end',this.value)"></div><div class="price-class-title">🚕 Vahid tam maşın qiyməti</div>${priceInput("Standart — Tək gediş",s.standard,i,"standard",onchange)}${priceInput("Standart — Gediş-dönüş",s.standard_round_trip,i,"standard_round_trip",onchange)}${priceInput("Comfort — Tək gediş",s.comfort,i,"comfort",onchange)}${priceInput("Comfort — Gediş-dönüş",s.comfort_round_trip,i,"comfort_round_trip",onchange)}${priceInput("VIP — Tək gediş",s.vip,i,"vip",onchange)}${priceInput("VIP — Gediş-dönüş",s.vip_round_trip,i,"vip_round_trip",onchange)}<button class="delete" onclick="${del}(${i})">🗑️ Sil</button></div>`;}
function renderSharedRouteSlots(){document.getElementById("qubaBakiSlots").innerHTML=data.prices.quba_baki.slots.map((s,i)=>slotHtml(s,i,"updateSharedRouteSlot","deleteSharedRouteSlot")).join("");changeSharedRouteDirection();}
function changeSharedRouteDirection(){const sel=document.getElementById("sharedRouteDirection");const title=document.getElementById("sharedRouteTitle");if(!sel||!title)return;title.textContent=sel.value==="baki_quba"?"💰 Bakı → Quba — Tam maşın tarifləri":"💰 Quba → Bakı — Tam maşın tarifləri";}
function updateSlot(slot,k,v){slot[k]=v;if(k==="standard")slot.one_way=v;if(k==="standard_round_trip")slot.round_trip=v;}
function updateSharedRouteSlot(i,k,v){updateSlot(data.prices.quba_baki.slots[i],k,v);data.prices.baki_quba=clone(data.prices.quba_baki);}
function deleteSharedRouteSlot(i){data.prices.quba_baki.slots.splice(i,1);data.prices.baki_quba=clone(data.prices.quba_baki);renderSharedRouteSlots();}
function addSharedRouteSlot(){data.prices.quba_baki.slots.push(emptySlot());data.prices.baki_quba=clone(data.prices.quba_baki);renderSharedRouteSlots();}
function addSlot(key){if(key==="quba_baki"||key==="baki_quba")return addSharedRouteSlot();data.prices[key].slots.push(emptySlot());}
function loadBakuLocations(selectedDistrict,selectedIndex){ensureBakuDistricts(false);const ds=document.getElementById("bakuDistrictSelect");ds.innerHTML="";BAKU_DISTRICTS.forEach(d=>ds.add(new Option(d,d)));if(selectedDistrict&&data.prices.baku_locations[selectedDistrict])ds.value=selectedDistrict;selectBakuDistrict(selectedIndex);}
function selectBakuDistrict(selectedIndex){const d=document.getElementById("bakuDistrictSelect").value;const ls=document.getElementById("bakuLocationSelect");ls.innerHTML="";const arr=data.prices.baku_locations[d]?.locations||[];arr.forEach((loc,i)=>ls.add(new Option(`${loc.name}${loc.type?" — "+loc.type:""}`,String(i))));if(arr.length){const idx=selectedIndex!==undefined&&selectedIndex>=0&&selectedIndex<arr.length?selectedIndex:0;ls.value=String(idx);}selectBakuLocation();}
function selectedBakuLocation(){const d=document.getElementById("bakuDistrictSelect").value;const i=Number(document.getElementById("bakuLocationSelect").value);const arr=data.prices.baku_locations[d]?.locations||[];return Number.isInteger(i)&&i>=0&&i<arr.length?{district:d,index:i,loc:arr[i]}:null;}
function selectBakuLocation(){const box=document.getElementById("bakuLocationEditor");const s=selectedBakuLocation();if(!s){box.innerHTML='<div class="baku-empty">Bu rayonda ünvan yoxdur. Yuxarıdan qəsəbə, küçə və ya prospekt əlavə edin.</div>';return;}const l=s.loc;box.innerHTML=`<div class="baku-selected-name">${esc(l.name)} <span class="mini-badge">${esc(l.type||"Digər")}</span></div><div class="baku-price-grid">${bakuPriceInput("Standart — Tək gediş",l.standard,"standard")}${bakuPriceInput("Standart — Gediş-dönüş",l.standard_round,"standard_round")}${bakuPriceInput("Comfort — Tək gediş",l.comfort,"comfort")}${bakuPriceInput("Comfort — Gediş-dönüş",l.comfort_round,"comfort_round")}${bakuPriceInput("VIP — Tək gediş",l.vip,"vip")}${bakuPriceInput("VIP — Gediş-dönüş",l.vip_round,"vip_round")}</div>`;}
function bakuPriceInput(label,value,key){return `<div><label>${label}</label><input inputmode="decimal" value="${esc(value)}" placeholder="AZN / tam maşın" onchange="updateBakuLocationPrice('${key}',this.value)"></div>`;}
function updateBakuLocationPrice(key,value){const s=selectedBakuLocation();if(!s)return;s.loc[key]=value;}
function addBakuLocation(){const d=document.getElementById("bakuDistrictSelect").value;const name=document.getElementById("newBakuLocationName").value.trim();const type=document.getElementById("bakuLocationType").value;if(!d)return alert("Bakı rayonu seçin");if(!name)return alert("Qəsəbə / küçə adını yazın");const arr=data.prices.baku_locations[d].locations;const existing=arr.findIndex(x=>String(x.name||"").localeCompare(name,"az",{sensitivity:"base"})===0);if(existing>=0){selectBakuDistrict(existing);return alert("Bu ünvan artıq siyahıdadır");}arr.push(normalizeBakuLocation({name,type}));document.getElementById("newBakuLocationName").value="";selectBakuDistrict(arr.length-1);}
function deleteSelectedBakuLocation(){const s=selectedBakuLocation();if(!s)return;if(confirm(`${s.district} / ${s.loc.name} silinsin?`)){data.prices.baku_locations[s.district].locations.splice(s.index,1);selectBakuDistrict();}}
function loadRegions(selected){const s=document.getElementById("regionSelect");s.innerHTML="";Object.keys(data.prices.regions).sort((a,b)=>a.localeCompare(b,"az")).forEach(r=>s.add(new Option(r,r)));if(selected&&data.prices.regions[selected])s.value=selected;selectRegion();}
function selectRegion(){const r=regionSelect.value;regionSlots.innerHTML=r?data.prices.regions[r].slots.map((s,i)=>slotHtml(s,i,"updateRegionSlot","deleteRegionSlot")).join(""):"";}
function updateRegionSlot(i,k,v){const r=regionSelect.value;if(r)updateSlot(data.prices.regions[r].slots[i],k,v);}function deleteRegionSlot(i){const r=regionSelect.value;if(r){data.prices.regions[r].slots.splice(i,1);selectRegion();}}function addRegionSlot(){const r=regionSelect.value;if(!r)return alert("Rayon seçin");data.prices.regions[r].slots.push(emptySlot());selectRegion();}
function addRegion(){const n=prompt("Rayon adı:");if(!n)return;const name=n.trim();if(!name)return;if(data.prices.regions[name])return alert("Bu rayon artıq mövcuddur");data.prices.regions[name]={slots:defaultSlots()};loadRegions(name);}function deleteSelectedRegion(){const r=regionSelect.value;if(r&&confirm(r+" silinsin?")){delete data.prices.regions[r];loadRegions();}}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
function loadServices(){const b=servicesList;data.services=data.services||[];b.innerHTML=data.services.map((x,i)=>`<div class="item"><input value="${esc(x.title||x.name)}" onchange="data.services[${i}].title=this.value"><input value="${esc(x.description)}" placeholder="Açıqlama" onchange="data.services[${i}].description=this.value"><input value="${esc(x.image)}" placeholder="Şəkil" onchange="data.services[${i}].image=this.value"><button class="delete" onclick="deleteService(${i})">🗑️ Sil</button></div>`).join("");}function addService(){data.services.push({title:"Yeni xidmət",description:"",image:""});loadServices();}function deleteService(i){data.services.splice(i,1);loadServices();}
function loadCars(){data.cars=data.cars||[];carsList.innerHTML=data.cars.map((x,i)=>`<div class="item"><input value="${esc(x.name)}" onchange="data.cars[${i}].name=this.value"><input value="${esc(x.image)}" onchange="data.cars[${i}].image=this.value"><input value="${esc(x.text||x.info)}" onchange="data.cars[${i}].text=this.value"><button class="delete" onclick="deleteCar(${i})">🗑️ Sil</button></div>`).join("");}function addCar(){data.cars.push({name:"Yeni avtomobil",image:"",text:""});loadCars();}function deleteCar(i){data.cars.splice(i,1);loadCars();}
function loadGallery(){data.gallery=data.gallery||[];galleryList.innerHTML=data.gallery.map((x,i)=>`<div class="item"><input value="${esc(x.title)}" onchange="data.gallery[${i}].title=this.value"><input value="${esc(x.url||x.image)}" onchange="data.gallery[${i}].url=this.value"><button class="delete" onclick="deleteGallery(${i})">🗑️ Sil</button></div>`).join("");}function addGallery(){data.gallery.push({title:"Yeni şəkil",url:""});loadGallery();}function deleteGallery(i){data.gallery.splice(i,1);loadGallery();}
function loadReviews(){data.reviews=data.reviews||[];reviewsList.innerHTML=data.reviews.map((x,i)=>`<div class="item"><input value="${esc(x.name)}" onchange="data.reviews[${i}].name=this.value"><input value="${esc(x.text||x.review)}" onchange="data.reviews[${i}].text=this.value"><button class="delete" onclick="deleteReview(${i})">🗑️ Sil</button></div>`).join("");}function addReview(){data.reviews.push({name:"",text:""});loadReviews();}function deleteReview(i){data.reviews.splice(i,1);loadReviews();}
function collectMain(){data.company.name=companyName.value;data.company.city=city.value;data.company.phone=phone.value;data.company.whatsapp=whatsapp.value;}
function prepareUnifiedPrices(){data.prices.baki_quba=clone(data.prices.quba_baki);data.pricingMode="full_car_unified";data.fullCarPrices=clone(data.prices);data.pricesUpdatedAt=Date.now();}
function saveData(){collectMain();prepareUnifiedPrices();fetch(API,{method:"POST",headers:{"Content-Type":"application/json","Authorization":adminAuth},body:JSON.stringify(data,null,4)}).then(async r=>{const t=await r.text();if(r.status===401||r.status===403)throw new Error("LOGIN_REQUIRED");if(!r.ok)throw new Error(t||r.status);alert("✅ Məlumatlar yadda saxlanıldı! Quba ↔ Bakı eyni tariflə, Bakı ünvanları isə ayrıca qiymətlə işləyir.");}).catch(e=>{if(e.message==="LOGIN_REQUIRED"){alert("Sessiya bitib. Yenidən daxil olun.");adminLogout();}else alert("❌ Yadda saxlama xətası: "+e.message);});}
