console.log("TAXI TIME ADMIN V5 işləyir");
let data={};
const defaultSlots=()=>[{start:"06:00",end:"20:00",one_way:"",round_trip:""},{start:"20:00",end:"00:00",one_way:"",round_trip:""},{start:"00:00",end:"06:00",one_way:"",round_trip:""}];
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".nav-btn").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".page").forEach(p=>p.classList.remove("active-page"));button.classList.add("active");document.getElementById(button.dataset.page)?.classList.add("active-page");}));loadDataFile();});
function oldPrice(v){if(v&&typeof v==="object"&&!Array.isArray(v))return {one_way:v.one_way||"",round_trip:v.round_trip||""};return {one_way:v||"",round_trip:""};}
function tariff(v){if(v&&Array.isArray(v.slots))return v;const p=oldPrice(v);const slots=defaultSlots();slots[0].one_way=p.one_way;slots[0].round_trip=p.round_trip;return {slots};}
function migrate(){data.company=data.company||{};data.prices=data.prices||{};data.prices.quba_baki=tariff(data.prices.quba_baki);data.prices.baki_quba=tariff(data.prices.baki_quba);data.prices.regions=data.prices.regions||{};Object.keys(data.prices.regions).forEach(r=>data.prices.regions[r]=tariff(data.prices.regions[r]));}
function loadDataFile(){fetch("data.json?ts="+Date.now()).then(r=>r.json()).then(j=>{data=j;migrate();loadData();}).catch(console.error);}
function loadData(){companyName.value=data.company.name||"";city.value=data.company.city||"";phone.value=data.company.phone||"";whatsapp.value=data.company.whatsapp||"";renderSlots("quba_baki","qubaBakiSlots");renderSlots("baki_quba","bakiQubaSlots");loadRegions();loadServices();loadCars();loadGallery();loadReviews();}
function slotHtml(s,i,onchange,del){return `<div class="tariff-row"><div><label>Başlanğıc</label><input type="time" value="${s.start||""}" onchange="${onchange}(${i},'start',this.value)"></div><div><label>Bitmə</label><input type="time" value="${s.end||""}" onchange="${onchange}(${i},'end',this.value)"></div><div><label>Tək gediş</label><input value="${esc(s.one_way)}" placeholder="Qiymət" onchange="${onchange}(${i},'one_way',this.value)"></div><div><label>Gediş-dönüş</label><input value="${esc(s.round_trip)}" placeholder="Qiymət" onchange="${onchange}(${i},'round_trip',this.value)"></div><button class="delete" onclick="${del}(${i})">🗑️ Sil</button></div>`;}
function renderSlots(key,id){document.getElementById(id).innerHTML=data.prices[key].slots.map((s,i)=>slotHtml(s,i,`updateMainSlot.bind(null,'${key}')`.replace(".bind(null,'"+key+"')",key==="quba_baki"?"updateQbSlot":"updateBqSlot"),key==="quba_baki"?"deleteQbSlot":"deleteBqSlot")).join("");}
function updateQbSlot(i,k,v){data.prices.quba_baki.slots[i][k]=v;}function updateBqSlot(i,k,v){data.prices.baki_quba.slots[i][k]=v;}
function deleteQbSlot(i){data.prices.quba_baki.slots.splice(i,1);renderSlots("quba_baki","qubaBakiSlots");}function deleteBqSlot(i){data.prices.baki_quba.slots.splice(i,1);renderSlots("baki_quba","bakiQubaSlots");}
function addSlot(key){data.prices[key].slots.push({start:"",end:"",one_way:"",round_trip:""});renderSlots(key,key==="quba_baki"?"qubaBakiSlots":"bakiQubaSlots");}
function loadRegions(selected){const s=document.getElementById("regionSelect");s.innerHTML="";Object.keys(data.prices.regions).sort((a,b)=>a.localeCompare(b,"az")).forEach(r=>s.add(new Option(r,r)));if(selected&&data.prices.regions[selected])s.value=selected;selectRegion();}
function selectRegion(){const r=regionSelect.value;regionSlots.innerHTML=r?data.prices.regions[r].slots.map((s,i)=>slotHtml(s,i,"updateRegionSlot","deleteRegionSlot")).join(""):"";}
function updateRegionSlot(i,k,v){const r=regionSelect.value;if(r)data.prices.regions[r].slots[i][k]=v;}function deleteRegionSlot(i){const r=regionSelect.value;if(r){data.prices.regions[r].slots.splice(i,1);selectRegion();}}function addRegionSlot(){const r=regionSelect.value;if(!r)return alert("Rayon seçin");data.prices.regions[r].slots.push({start:"",end:"",one_way:"",round_trip:""});selectRegion();}
function addRegion(){const n=prompt("Rayon adı:");if(!n)return;const name=n.trim();if(!name)return;if(data.prices.regions[name])return alert("Bu rayon artıq mövcuddur");data.prices.regions[name]={slots:defaultSlots()};loadRegions(name);}function deleteSelectedRegion(){const r=regionSelect.value;if(r&&confirm(r+" silinsin?")){delete data.prices.regions[r];loadRegions();}}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function loadServices(){const b=servicesList;data.services=data.services||[];b.innerHTML=data.services.map((x,i)=>`<div class="item"><input value="${esc(x.title||x.name)}" onchange="data.services[${i}].title=this.value"><input value="${esc(x.description)}" placeholder="Açıqlama" onchange="data.services[${i}].description=this.value"><input value="${esc(x.image)}" placeholder="Şəkil" onchange="data.services[${i}].image=this.value"><button class="delete" onclick="deleteService(${i})">🗑️ Sil</button></div>`).join("");}function addService(){data.services.push({title:"Yeni xidmət",description:"",image:""});loadServices();}function deleteService(i){data.services.splice(i,1);loadServices();}
function loadCars(){data.cars=data.cars||[];carsList.innerHTML=data.cars.map((x,i)=>`<div class="item"><input value="${esc(x.name)}" onchange="data.cars[${i}].name=this.value"><input value="${esc(x.image)}" onchange="data.cars[${i}].image=this.value"><input value="${esc(x.text||x.info)}" onchange="data.cars[${i}].text=this.value"><button class="delete" onclick="deleteCar(${i})">🗑️ Sil</button></div>`).join("");}function addCar(){data.cars.push({name:"Yeni avtomobil",image:"",text:""});loadCars();}function deleteCar(i){data.cars.splice(i,1);loadCars();}
function loadGallery(){data.gallery=data.gallery||[];galleryList.innerHTML=data.gallery.map((x,i)=>`<div class="item"><input value="${esc(x.title)}" onchange="data.gallery[${i}].title=this.value"><input value="${esc(x.url||x.image)}" onchange="data.gallery[${i}].url=this.value"><button class="delete" onclick="deleteGallery(${i})">🗑️ Sil</button></div>`).join("");}function addGallery(){data.gallery.push({title:"Yeni şəkil",url:""});loadGallery();}function deleteGallery(i){data.gallery.splice(i,1);loadGallery();}
function loadReviews(){data.reviews=data.reviews||[];reviewsList.innerHTML=data.reviews.map((x,i)=>`<div class="item"><input value="${esc(x.name)}" onchange="data.reviews[${i}].name=this.value"><input value="${esc(x.text||x.review)}" onchange="data.reviews[${i}].text=this.value"><button class="delete" onclick="deleteReview(${i})">🗑️ Sil</button></div>`).join("");}function addReview(){data.reviews.push({name:"",text:""});loadReviews();}function deleteReview(i){data.reviews.splice(i,1);loadReviews();}
function collectMain(){data.company.name=companyName.value;data.company.city=city.value;data.company.phone=phone.value;data.company.whatsapp=whatsapp.value;}
function saveData(){collectMain();fetch("https://taxitime-api.taxitime0711.workers.dev",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data,null,4)}).then(async r=>{const t=await r.text();if(!r.ok)throw new Error(t||r.status);alert("✅ Məlumatlar yadda saxlanıldı!");}).catch(e=>alert("❌ Yadda saxlama xətası: "+e.message));}
