// TAXI TIME public tariffs: Bakı + Azərbaycan rayonları, sərbəst Haradan/Hara
function ttPriceKey(slot,cls,trip){const c=cls||'standard';if(c==='standard')return trip==='round_trip'?'standard_round_trip':'standard';if(c==='comfort')return trip==='round_trip'?'comfort_round_trip':'comfort';return trip==='round_trip'?'vip_round_trip':'vip';}
function ttSlotValue(slot,cls,trip){const key=ttPriceKey(slot,cls,trip);if(slot&&slot[key])return slot[key];if(cls==='standard')return trip==='round_trip'?(slot.round_trip||''):(slot.one_way||'');return '';}
function ttNorm(v){return String(v||'').toLocaleLowerCase('az').replace(/ı/g,'i').replace(/ə/g,'e').replace(/ş/g,'s').replace(/ç/g,'c').replace(/ğ/g,'g').replace(/ö/g,'o').replace(/ü/g,'u');}
async function ttFetchData(){const r=await fetch('data.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Tarif məlumatı alınmadı');return r.json();}
function ttBakuFallback(){const x={"Binəqədi":["Biləcəri","Binəqədi qəsəbəsi","6-cı mikrorayon","7-ci mikrorayon","8-ci mikrorayon","9-cu mikrorayon"],"Qaradağ":["Lökbatan","Sahil","Ələt","Puta"],"Xəzər":["Mərdəkan","Buzovna","Şüvəlan","Türkan","Qala","Zirə"],"Səbail":["İçərişəhər","Bayıl","Badamdar"],"Sabunçu":["Bakıxanov","Zabrat","Ramana","Maştağa","Bilgəh","Nardaran","Pirşağı"],"Suraxanı":["Hövsan","Yeni Günəşli","Əmircan","Bülbülə","Zığ"],"Xətai":["Əhmədli","Həzi Aslanov","Ağ Şəhər"],"Nizami":["8-ci kilometr","Qara Qarayev","Neftçilər","Keşlə"],"Nərimanov":["Gənclik","Montin","Böyükşor","Nərimanov"],"Nəsimi":["28 May","3-cü mikrorayon"],"Yasamal":["Yasamal","Yeni Yasamal","Elmlər Akademiyası"],"Pirallahı":["Pirallahı"]};const o={};Object.keys(x).forEach(d=>o[d]={locations:x[d].map(n=>({name:n,standard:'',comfort:'',vip:'',standard_round:'',comfort_round:'',vip_round:''}))});return o;}
function ttGetBaku(data){const b=data.prices?.baku_locations;return b&&Object.keys(b).length?b:ttBakuFallback();}
function ttBakuValue(x,cls,trip){if(!x)return '';if(trip==='round_trip'){if(cls==='standard')return x.standard_round||'';if(cls==='comfort')return x.comfort_round||'';return x.vip_round||'';}return x[cls]||'';}
function ttFindBakuLocation(baku,name){for(const d of Object.keys(baku||{})){const a=baku[d]?.locations||[];const x=a.find(v=>v.name===name);if(x)return x;}return null;}
function ttRouteTariff(data,from,to){const p=data.prices||{},r=p.regions||{};if((from==='Quba'&&to==='Bakı')||(from==='Bakı'&&to==='Quba'))return p.quba_baki;if(from==='Quba'&&r[to])return r[to];if(to==='Quba'&&r[from])return r[from];return null;}
function loadPrices(){const box=document.getElementById('priceList');if(!box)return;ttFetchData().then(data=>{const regions=Object.keys(data.prices?.regions||{}).filter(x=>x!=='Bakı'&&x!=='Quba').sort((a,b)=>a.localeCompare(b,'az'));const baku=ttGetBaku(data);const districts=Object.keys(baku).sort((a,b)=>a.localeCompare(b,'az'));const regionPlaces=['Quba','Bakı',...regions];const placeOpts=regionPlaces.map(x=>`<option value="${safeText(x)}">${safeText(x)}</option>`).join('');
box.innerHTML=`<div class="tt-public-grid"><div class="price-card tt-tariff-card"><h3>🏙️ Bakı</h3><p>Bakı ilə istənilən istiqamət üzrə tarif</p><label>Haradan</label><select id="ttBakuFrom">${placeOpts}</select><label>Hara</label><select id="ttBakuTo">${placeOpts}</select><div id="ttBakuAddressWrap"><select id="ttBakuDistrict"></select><select id="ttBakuLocation"></select></div><select id="ttBakuClass"><option value="standard">Standart</option><option value="comfort">Comfort</option><option value="vip">VIP</option></select><select id="ttBakuTrip"><option value="one_way">Tək gediş</option><option value="round_trip">Gediş-dönüş</option></select><h2 id="ttBakuPrice">Marşrut seçin</h2><p id="ttBakuTime"></p></div><div class="price-card tt-tariff-card"><h3>🌍 Azərbaycanın rayonları</h3><p>Rayonlar arasında istiqamət seçin</p><label>Haradan</label><select id="ttRegionFrom">${placeOpts}</select><label>Hara</label><select id="ttRegionTo">${placeOpts}</select><select id="ttRegionClass"><option value="standard">Standart</option><option value="comfort">Comfort</option><option value="vip">VIP</option></select><select id="ttRegionTrip"><option value="one_way">Tək gediş</option><option value="round_trip">Gediş-dönüş</option></select><h2 id="ttRegionPrice">Marşrut seçin</h2><p id="ttRegionTime"></p></div></div>`;
const bf=document.getElementById('ttBakuFrom'),bto=document.getElementById('ttBakuTo'),bd=document.getElementById('ttBakuDistrict'),bl=document.getElementById('ttBakuLocation'),bc=document.getElementById('ttBakuClass'),bt=document.getElementById('ttBakuTrip'),bp=document.getElementById('ttBakuPrice'),btime=document.getElementById('ttBakuTime'),bw=document.getElementById('ttBakuAddressWrap');bf.value='Quba';bto.value='Bakı';bd.innerHTML='<option value="">Bakı rayonu seçin</option>'+districts.map(x=>`<option value="${safeText(x)}">${safeText(x)}</option>`).join('');
function loadLoc(){const d=bd.value,a=d?(baku[d]?.locations||[]):[];bl.innerHTML='<option value="">Qəsəbə / məhəllə / küçə seçin</option>'+a.map(x=>`<option value="${safeText(x.name||'')}">${safeText(x.name||'')}</option>`).join('');showBaku();}
async function showBaku(){const from=bf.value,to=bto.value;if(from===to){bp.textContent='Fərqli məntəqə seçin';btime.textContent='';return;}const involvesBaku=from==='Bakı'||to==='Bakı';bw.style.display=involvesBaku?'block':'none';try{const fresh=await ttFetchData();const freshBaku=ttGetBaku(fresh);let val='',label='';if(involvesBaku&&bl.value){const x=ttFindBakuLocation(freshBaku,bl.value);val=ttBakuValue(x,bc.value,bt.value);}if(!val){const tariff=ttRouteTariff(fresh,from,to);if(tariff){const s=activeSlot(tariff);val=ttSlotValue(s,bc.value,bt.value);label=slotLabel(s);}}bp.textContent=val?`Qiymət: ${val}`:'Qiymət daxil edilməyib';btime.textContent=label?`Aktiv tarif: ${label}`:'';}catch(e){bp.textContent='Qiymət yenilənmədi';}}
bd.addEventListener('change',loadLoc);bl.addEventListener('change',showBaku);bf.addEventListener('change',showBaku);bto.addEventListener('change',showBaku);bc.addEventListener('change',showBaku);bt.addEventListener('change',showBaku);loadLoc();
const rf=document.getElementById('ttRegionFrom'),rt=document.getElementById('ttRegionTo'),rc=document.getElementById('ttRegionClass'),rtrip=document.getElementById('ttRegionTrip'),rp=document.getElementById('ttRegionPrice'),rtime=document.getElementById('ttRegionTime');rf.value='Quba';rt.value=regions[0]||'Bakı';async function showRegion(){const from=rf.value,to=rt.value;if(from===to){rp.textContent='Fərqli məntəqə seçin';rtime.textContent='';return;}try{const fresh=await ttFetchData();const tariff=ttRouteTariff(fresh,from,to);if(!tariff){rp.textContent='Bu marşrut üçün tarif yoxdur';rtime.textContent='';return;}const s=activeSlot(tariff),v=ttSlotValue(s,rc.value,rtrip.value);rp.textContent=v?`Qiymət: ${v}`:'Qiymət daxil edilməyib';rtime.textContent=slotLabel(s)?`Aktiv tarif: ${slotLabel(s)}`:'';}catch(e){rp.textContent='Qiymət yenilənmədi';}}rf.addEventListener('change',showRegion);rt.addEventListener('change',showRegion);rc.addEventListener('change',showRegion);rtrip.addEventListener('change',showRegion);showRegion();
}).catch(console.log);}
