function loadCars(){const box=document.getElementById("carsBox");if(!box)return;fetch("data.json?ts="+Date.now()).then(r=>r.json()).then(data=>{box.innerHTML="";(data.cars||[]).forEach(car=>box.innerHTML+=`<div class="fleet-card"><img src="${car.image}" alt="${car.name}"><h3>${car.name}</h3><p>${car.text||car.info||""}</p></div>`);}).catch(console.log);}
function loadServices(){const box=document.getElementById("servicesBox");if(!box)return;fetch("data.json?ts="+Date.now()).then(r=>r.json()).then(data=>{box.innerHTML="";(data.services||[]).forEach(s=>box.innerHTML+=`<div class="card"><img src="${s.image||""}" alt="${s.title||s.name||""}"><h3>${s.title||s.name||""}</h3><p>${s.description||""}</p></div>`);}).catch(console.log);}
function normPrice(v){return v&&typeof v==="object"?{one_way:v.one_way||"",round_trip:v.round_trip||""}:{one_way:v||"",round_trip:""};}
function loadPrices(){const box=document.getElementById("priceList");if(!box)return;fetch("data.json?ts="+Date.now()).then(r=>r.json()).then(data=>{const qb=normPrice(data.prices.quba_baki),bq=normPrice(data.prices.baki_quba);let opts='<option value="">Rayon seçin</option>';Object.keys(data.prices.regions||{}).sort((a,b)=>a.localeCompare(b,"az")).forEach(r=>opts+=`<option value="${r}">${r}</option>`);box.innerHTML=`
<div class="price-card"><h3>Quba → Bakı</h3><select id="qbTrip"><option value="one_way">Tək gediş</option><option value="round_trip">Gediş-dönüş</option></select><h2 id="qbPrice"></h2><p>Səfər növünü seçin</p></div>
<div class="price-card"><h3>Bakı → Quba</h3><select id="bqTrip"><option value="one_way">Tək gediş</option><option value="round_trip">Gediş-dönüş</option></select><h2 id="bqPrice"></h2><p>Səfər növünü seçin</p></div>
<div class="price-card"><h3>🌍 Bölgələr</h3><select id="regionSelect">${opts}</select><select id="regionTrip"><option value="one_way">Tək gediş</option><option value="round_trip">Gediş-dönüş</option></select><h2 id="regionPrice">Rayon seçin</h2><p>Rayon və səfər növünü seçin</p></div>`;
const showMain=(sel,id,p)=>{document.getElementById(id).textContent=p[document.getElementById(sel).value]||"Qiymət daxil edilməyib";};
document.getElementById("qbTrip").onchange=()=>showMain("qbTrip","qbPrice",qb);document.getElementById("bqTrip").onchange=()=>showMain("bqTrip","bqPrice",bq);showMain("qbTrip","qbPrice",qb);showMain("bqTrip","bqPrice",bq);
const showRegion=()=>{const r=document.getElementById("regionSelect").value,t=document.getElementById("regionTrip").value,p=document.getElementById("regionPrice");if(!r){p.textContent="Rayon seçin";return;}p.textContent=normPrice(data.prices.regions[r])[t]||"Qiymət daxil edilməyib";};document.getElementById("regionSelect").onchange=showRegion;document.getElementById("regionTrip").onchange=showRegion;
}).catch(console.log);}
function sendOrder(){const name=document.getElementById("name").value.trim(),phone=document.getElementById("phone").value.trim(),from=document.getElementById("from").value.trim(),to=document.getElementById("to").value.trim(),date=document.getElementById("date").value,time=document.getElementById("time").value,person=document.getElementById("person").value,car=document.getElementById("car").value;if(!name||!phone||!from||!to){alert("Zəhmət olmasa bütün vacib məlumatları doldurun.");return;}const message=`Salam TAXI TIME\n\nAd: ${name}\nTelefon: ${phone}\nMarşrut: ${from} → ${to}\nTarix: ${date}\nSaat: ${time}\nSərnişin sayı: ${person}\nAvtomobil: ${car}`;window.open("https://wa.me/994507119711?text="+encodeURIComponent(message),"_blank");}
function startCounters(){document.querySelectorAll(".counter").forEach(c=>{const target=Number(c.dataset.target);let count=0;const speed=Math.max(1,Math.ceil(target/100));const timer=setInterval(()=>{count+=speed;if(count>=target){count=target;clearInterval(timer);}c.textContent=count+"+";},20);});}
function initLightbox(){const l=document.getElementById("lightbox"),img=document.getElementById("lightbox-img"),close=document.querySelector(".close");if(!l||!img)return;document.querySelectorAll(".gallery-item img").forEach(i=>i.addEventListener("click",()=>{l.style.display="flex";img.src=i.src;}));if(close)close.onclick=()=>l.style.display="none";l.onclick=e=>{if(e.target===l)l.style.display="none";};}
document.addEventListener("DOMContentLoaded",()=>{loadServices();loadCars();loadPrices();startCounters();initLightbox();});
